Models/CalcDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace HourCalcMVC.Models
{
    public class CalcDbContext : DbContext
    {
        public DbSet<DailyHour> dailyHours {get; set;}

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            //ToDo: Change Database name
        {
            optionsBuilder.UseSqlite("Data Source=Data/DatabaseTesting.db;");
        }
    }
}

Models/DailyHour.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SQLite;

namespace HourCalcMVC.Models
{
    public class DailyHour
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        public DateTime StartingHour { get; set; }
        public DateTime EndingHour { get; set; }
        public string? Total { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;
        public string? Shift { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace HourCalcMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalculatorController.cs
using Azure;
using HourCalcMVC.Models;
using HourCalcMVC.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace HourCalcMVC.Controllers
{
    public class CalculatorController : Controller
    {
        public int response = 1;
        private readonly CalcDbContext _dbContext;
        private readonly IDatabaseService _databaseService;
        public CalculatorController(CalcDbContext dbContext, IDatabaseService databaseService) 
        {
            _dbContext = dbContext;
            _databaseService = databaseService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {

            return View(await _databaseService.GetAll());
        }
        public IActionResult Add()
        {
            return View();
        }
        public async Task<IActionResult> Details(int? Id)
        { 
            ViewBag.Id = Id;
            return View(await _databaseService.GetAll());
        }
        public async Task<IActionResult> Delete(int? Id)
        {
            ViewBag.Id = Id;
            var delete = await _databaseService.GetAll();
            return View(delete.Where(d => d.Id == Id));
        }
        [HttpPost]
        public async Task<IActionResult> Add(DailyHour dailyHour)
        {
            
            if (dailyHour.Shift == "First")
            {
                dailyHour.StartingHour = new DateTime(2001, 1, 01, 6, 00, 00);
                dailyHour.EndingHour = new DateTime(2001, 1, 01, 14, 30, 00);
                var a = TimeOnly.FromDateTime(dailyHour.EndingHour) - TimeOnly.FromDateTime(dailyHour.StartingHour);
                dailyHour.Total = a.ToString();
                response = await _databaseService.Add(dailyHour);
            }
            else if (dailyHour.Shift == "Second")
            {
                dailyHour.StartingHour = new DateTime(2001, 1, 01, 14, 30, 00);
                dailyHour.EndingHour = new DateTime(2001, 1, 01, 23, 00, 00);
                var a = TimeOnly.FromDateTime(dailyHour.EndingHour) - TimeOnly.FromDateTime(dailyHour.StartingHour);
                dailyHour.Total = a.ToString();
                response = await _databaseService.Add(dailyHour);
            }
            else if(dailyHour.Shift == "Custom")
            {
                var a = TimeOnly.FromDateTime(dailyHour.StartingHour);
                var b = TimeOnly.FromDateTime(dailyHour.EndingHour);
                var c = b - a;
                dailyHour.Total = c.ToString();
                response = await _databaseService.Add(dailyHour);
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            response = await _databaseService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Calculator/Add.cshtml
@model HourCalcMVC.Models.DailyHour;

@{
    ViewData["Title"] = "Add Hours";
}

<div class="row text-center m-auto p-2">
    <div class="col-md-4 text-center">
    <h1 class="display-4">Add Day</h1>
    <form asp-action="Add">
        <div class="form-group">
                <label class="form-label" asp-for="Shift">First</label>
            <input type="radio" asp-for="Shift" value="First" id="Shift" />
                <label class="form-label" asp-for="Shift">Second</label>
            <input type="radio" asp-for="Shift" value="Second" id="Shift" />
                <label class="form-label" asp-for="Shift">Custom</label>
            <input type="radio" asp-for="Shift" value="Custom" id="Shift" checked="checked" />
        </div>
        <div class="form-group">
            <label class="form-label" asp-for="StartingHour"></label>
            <input class="form-control" asp-for="StartingHour" type="time" />
        </div>
        <div class="form-group">
            <label class="form-label" asp-for="EndingHour"></label>
            <input class="form-control" asp-for="EndingHour" type="time" />
        </div>
        <div class="form-group">
            <label class="form-label" asp-for="Date"></label>
            <input class="form-control" asp-for="Date" type="date" />
        </div>
        <div><input type="submit" value="Add" class="btn btn-primary" /></div>
    </form>
    </div>
</div>

Views/Calculator/Delete.cshtml
@model IEnumerable<HourCalcMVC.Models.DailyHour>;
@{
    ViewData["Title"] = "Delete";
    var id = ViewBag.Id;
}
<div class="text-center">
    <h1 class="display-4">Are you sure?</h1>
</div>
@foreach (var item in Model)
{
    <div class="content text-center m-2 p-2">
        <form asp-action="DeleteConfirmed">
            <input type="hidden" asp-for="@id" />
            <input class="btn btn-danger" type="submit" value="Delete" />
            <a asp-action="Index" class="btn btn-primary">Cancel</a>
        </form>
    </div>
}

Views/Calculator/Details.cshtml
@model IEnumerable<HourCalcMVC.Models.DailyHour>;

@{
    ViewData["Title"] = "Work Hour Calculator";
    var id = ViewBag.Id;
    int hours = 0;
    int minutes = 0;
    int firstShift = 0;
    int secondShift = 0;
    TimeSpan TotalTime = new TimeSpan();

    var months = new Dictionary<int, string>
    {
                {1, "Styczeń" },
                {2, "Luty" },
                {3, "Marzec" },
                {4, "Kwiecień" },
                {5, "Maj" },
                {6, "Czerwiec" },
                {7, "Lipiec" },
                {8, "Sierpień" },
                {9, "Wrzesień" },
                {10, "Październik" },
                {11, "Listopad" },
                {12, "Grudzień" },
    };
    var mon = months.FirstOrDefault(m => m.Key == id).Value;
    @foreach (var item in Model.Where(m => m.Date.Month == id))
    {
        hours += DateTime.Parse(item.Total).Hour;
        minutes += DateTime.Parse(item.Total).Minute;
        TotalTime = TotalTime.Add(TimeOnly.FromDateTime(DateTime.Parse(item.Total)).ToTimeSpan());
        if(item.Shift == "First")
        {
            firstShift += 1;
        }
        else if(item.Shift == "Second")
        {
            secondShift += 1;
        }
    }
}
@if (TotalTime.Days >= 1)
{
    hours = TotalTime.Days * 24 + TotalTime.Hours;
    minutes = TotalTime.Minutes;
}
else
{
    hours = TotalTime.Hours;
    minutes = TotalTime.Minutes;
}
<div class="text-center">
    <h1 class="display-4">@mon</h1>
     @if(minutes == 0)
        {
        <h4>
            Total time @hours.ToString("00")
        </h4>
        }else
        {
        <h4>
            Total time @hours.ToString("00"):@minutes.ToString("00")
        </h4>
        }
    <p>Ilość pierwszych zmian: @firstShift</p>
    <p>Ilość drugich zmian: @secondShift</p>

    
</div>
@foreach (var item in Model.Where(m => m.Date.Month == id).OrderBy(d => d.Date))
{
    <div class="rounded border border-dark p-2 m-2 bg-main">
        <p>Started at: @item.StartingHour.ToString("HH:mm")</p>
        <p>Ended at: @item.EndingHour.ToString("HH:mm")</p>
        <p>@item.Date.ToString("d")</p>
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
    </div>
}

Views/Calculator/Index.cshtml
@model IEnumerable<HourCalcMVC.Models.DailyHour>;

@{
    ViewData["Title"] = "Work Hour Calculator";
    var months = new Dictionary<int, string>
    {
                {1, "Styczeń" },
                {2, "Luty" },
                {3, "Marzec" },
                {4, "Kwiecień" },
                {5, "Maj" },
                {6, "Czerwiec" },
                {7, "Lipiec" },
                {8, "Sierpień" },
                {9, "Wrzesień" },
                {10, "Październik" },
                {11, "Listopad" },
                {12, "Grudzień" },
    };
}

<div class="text-center">
    <h1 class="display-4">Choose month</h1>
</div>
@foreach(var item in months)
{
    int id = 0;
    int hours = 00;
    int minutes = 00;
    TimeSpan TotalTime = new TimeSpan();
    @foreach (var time in Model.Where(m => m.Date.Month == item.Key))
    {
        var a = TimeOnly.Parse(time.Total);
        TotalTime = TotalTime.Add(a.ToTimeSpan());
        @if (TotalTime.Days >= 1)
        {
            hours = TotalTime.Days * 24 + TotalTime.Hours;
            minutes = TotalTime.Minutes;
        }
        else
        {
            hours = TotalTime.Hours;
            minutes = TotalTime.Minutes;
        }
        id = item.Key;
    }
    <div class="rounded border border-dark p-2 m-2 bg-main">
        <p>@item.Value</p><p>Monthly Working Time: @hours.ToString("00"):@minutes.ToString("00")</p>
        <a class="btn btn-primary" asp-action="Details" asp-route-id="@id">GoTo...</a>
    </div>

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HourCalcMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HourCalcMVC.styles.css" asp-append-version="true" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Calculator" asp-action="Index">HourCalcMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Add">Add day</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HourCalcMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>